export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS"
export const GET_GROUPS_FAIL = "GET_GROUPS_FAIL"

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_PRESENTATIONS_SUCCESS = "GET_PRESENTATIONS_SUCCESS"
export const GET_PRESENTATIONS_FAIL = "GET_PRESENTATIONS_FAIL"

export const GET_TESTS_SUCCESS = "GET_TESTS_SUCCESS"
export const GET_TESTS_FAIL = "GET_TESTS_FAIL"

export const GET_TEST_SUCCESS = "GET_TEST_SUCCESS"
export const GET_TEST_FAIL = "GET_TEST_FAIL"