CREATE USER ord WITH password 'qkWZeZ1v';

GRANT ALL PRIVILEGES ON DATABASE ord TO ord;
GRANT ALL PRIVILEGES ON schema public TO ord;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ord;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ord;